name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: pre-checkout (For Demostraction)
        run: |
          pwd
          ls -lh # 修正 PowerShell 指令 Get-ChildItem | Format-Table -AutoSize
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: after-checkout (For Demostraction)
        run: |
          pwd
          ls -lh # 修正 PowerShell 指令 Get-ChildItem | Format-Table -AutoSize
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: |
          npm ci
          echo "Install dependencies"
      - name: Install Playwright Browsers
        run: |
          npx playwright install --with-deps
          echo "Install Playwright Browsers"
      - name: Run Playwright tests one
        run: |
          npx playwright test one
          echo "Run Playwright tests one"
      - name: Run Playwright tests example
        run: |
          npx playwright test example
          echo "Run Playwright tests example"
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
